---
- name: Installer zsh et utilitaires
  become: yes
  pacman:
    name:
      - zsh
      - wget
      - git
    state: present

- name: Définir zsh comme shell par défaut pour l'utilisateur specifie
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Installer oh-my-zsh
  become: no
  environment:
    HOME: "/home/{{ ansible_user }}"
    USER: "{{ ansible_user }}"
  shell: |
    sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" "" --unattended
  args:
    chdir: "/home/{{ ansible_user }}"
    creates: "/home/{{ ansible_user }}/.oh-my-zsh"
