---
- name: Activer le depot multilib dans pacman.conf
  become: yes
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#?\s*\[multilib\]'
    replace: '[multilib]'
  notify: Update pacman cache

- name: Decommenter la ligne include du depot multilib
  become: yes
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#?\s*Include = /etc/pacman.d/mirrorlist'
    replace: 'Include = /etc/pacman.d/mirrorlist'
  notify: Update pacman cache

- name: Mettre a jour la liste des paquets (pacamn -Sy)
  become: yes
  ansible.builtin.command: pacman -Sy
  when: false

- name: Installer Steam
  become: yes
  pacman:
    name: steam
    state: present

- name: Installer Lutris
  become: yes
  pacman:
    name: lutris
    state: present

- name: Installer MangoHud (overlay de performance)
  become: yes
  pacman:
    name: mangohud
    state: present

- name: Installer ProtonUp-Qt (gestionnaire de versions Proton)
  become: no
  kewlfft.aur.aur:
    name: protonup-qt
    use: yay

- name: Installer Heroic Games Launcher (Epic, GOG, Amazon)
  become: no
  kewlfft.aur.aur:
    name: heroic-games-launcher-bin
    use: yay

- name: Installer quelques dépendances utiles pour le gaming
  become: yes
  pacman:
    name:
      - wine
      - winetricks
      - gamemode
      - lib32-vulkan-icd-loader
      - vulkan-icd-loader
      - lib32-vulkan-driver
      - vulkan-driver
      - lib32-nvidia-utils
      - nvidia-utils
    state: present
