---
- name: Installer Steam
  become: yes
  pacman:
    name: steam
    state: present

- name: Installer Lutris
  become: yes
  pacman:
    name: lutris
    state: present

- name: Installer MangoHud (overlay de performance)
  become: yes
  pacman:
    name: mangohud
    state: present

- name: Installer ProtonUp-Qt (gestionnaire de versions Proton)
  become: yes
  pacman:
    name: protonup-qt
    state: present

- name: Installer Heroic Games Launcher (Epic, GOG, Amazon)
  become: yes
  pacman:
    name: heroic-games-launcher-bin
    state: present

- name: Installer quelques dépendances utiles pour le gaming
  become: yes
  pacman:
    name:
      - wine
      - winetricks
      - gamemode
      - lib32-vulkan-icd-loader
      - vulkan-icd-loader
      - lib32-vulkan-driver
      - vulkan-driver
      - lib32-nvidia-utils
      - nvidia-utils
    state: present