---
- name: Installer Docker et Docker Compose
  become: yes
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Activer et démarrer le service Docker
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ajouter l'utilisateur courant au groupe docker
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Installer PhpStorm depuis l'AUR
  kewlfft.aur.aur:
    name: phpstorm
    use: yay

- name: Installer Beekeeper Studio depuis l'AUR
  kewlfft.aur.aur:
    name: beekeeper-studio-bin
    use: yay

- name: Installer Brave depuis l'AUR
  kewlfft.aur.aur:
    name: brave-bin
    use: yay