---
- name: installer fuse-overlayfs
  become: yes
  pacman:
    name: fuse-overlayfs
    state: present

- name: Installer le JRE jetbrains
  become: false
  kewlfft.aur.aur:
    name: phpstorm-jre
    use: yay

- name: Charger les modules kernel necessaires pour Docker
  become: yes
  modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter
    - ip_tables
    - nf_nat

- name: Installer Docker et Docker Compose
  become: yes
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Activer et démarrer le service Docker
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Ajouter l'utilisateur courant au groupe docker
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Installer PhpStorm depuis l'AUR
  kewlfft.aur.aur:
    name: phpstorm
    use: yay
  become: false

- name: Installer Beekeeper Studio depuis l'AUR
  kewlfft.aur.aur:
    name: beekeeper-studio-bin
    use: yay
  become: false

- name: Installer Brave depuis l'AUR
  kewlfft.aur.aur:
    name: brave-bin
    use: yay
  become: false
