---
- name: Mettre à jour le système
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Installer les paquets de base
  become: yes
  pacman:
    name:
      - base-devel
      - git
      - curl
      - htop
      - ranger
      - bat
      - fzf
      - zsh
      - wget
      - unzip
      - alacritty
      - rofi
      - networkmanager
      - openssh
      - sudo
      - which
      - python
      - python-pip
    state: present

- name: Activer NetworkManager
  become: yes
  systemd:
    name: NetworkManager
    enabled: yes
    state: started

- name: Installer yay (AUR helper)
  become: no
  block:
    - name: Vérifier si yay est déjà installé
      stat:
        path: /usr/bin/yay
      register: yay_installed

    - name: Cloner yay depuis AUR
      git:
        repo: https://aur.archlinux.org/yay.git
        dest: "/home/{{ ansible_user }}/yay"
        update: yes
      when: not yay_installed.stat.exists

    - name: Compiler et installer yay
      become: no
      shell: |
        cd /home/{{ ansible_user }}/yay
        makepkg -si --noconfirm
      args:
        creates: /usr/bin/yay
      when: not yay_installed.stat.exists

    - name: Nettoyer le dossier yay
      file:
        path: "/home/{{ ansible_user }}/yay"
        state: absent
      when: yay_installed.stat.exists == False
